SELECT * FROM ROUTES;
SELECT * FROM ROUTES_PERFIL;
SELECT * FROM PERFIL;
SELECT * FROM USUÁRIO_PERFIL;
SELECT * FROM USUÁRIO;
SELECT * FROM UNIDADE;
SELECT * FROM USUÁRIO_UNIDADE;
SELECT * FROM MENU;


SELECT USERxID.*, UNIDADE.NOME, USUARIO.NOME 
FROM USUÁRIO_UNIDADE AS USERxID
INNER JOIN USUÁRIO AS 
USUARIO ON (USERxID.IDUSUÁRIO = USUARIO.ID)
INNER JOIN UNIDADE AS UNIDADE ON 
(USERxID.IDUNIDADE = UNIDADE.ID);

SELECT 
UNIDADE.NOME AS NomeUnidade, 
USUÁRIO.NOME AS NomeUsuario
FROM USUÁRIO_UNIDADE 
INNER JOIN USUÁRIO ON (USUÁRIO_UNIDADE.IDUSUÁRIO = USUÁRIO.ID)
INNER JOIN UNIDADE ON 
(UNIDADE.ID = UNIDADE.ID);


SELECT USERxID.*, PERFIL.NOME, USUARIO.NOME 
FROM USUÁRIO_PERFIL AS USERxID
INNER JOIN USUÁRIO AS 
USUARIO ON (USERxID.IDUSUÁRIO = USUARIO.ID)
INNER JOIN PERFIL AS PERFIL ON 
(USERxID.IDPERFIL = PERFIL.ID);

SELECT USUÁRIO.NOME AS NomeUsuario,
PERFIL.NOME AS NomePerfil 
FROM USUÁRIO_PERFIL
INNER JOIN USUÁRIO ON (USUÁRIO_PERFIL.IDUSUÁRIO = USUÁRIO.ID)
INNER JOIN PERFIL ON (USUÁRIO_PERFIL.IDPERFIL = PERFIL.ID)


SELECT USUÁRIO.ID AS IdUsuario,
PERFIL.ID AS IdPerfil
FROM USUÁRIO_PERFIL
INNER JOIN USUÁRIO ON (USUÁRIO_PERFIL.IDUSUÁRIO = USUÁRIO.ID)
INNER JOIN PERFIL ON(USUÁRIO_PERFIL.IDPERFIL = PERFIL.ID)
WHERE USUÁRIO.ID=1 AND USUÁRIO.NOME='João'
